# Generated by Django 5.2.4 on 2025-08-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('id',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('submission_id',), 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ('id',), 'verbose_name': 'Homework', 'verbose_name_plural': 'Homeworks'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ('id',), 'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('id',), 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
    ]
