# Generated by Django 5.2.4 on 2025-10-10 07:37

from django.db import migrations

from courses.models import Course


def make_course_title_lowercase(apps, schema_editor):
    for course in Course.objects.all():
        course.title = course.title.lower()
        course.save(update_fields=['title'])

def course_title_capitalize(apps, schema_editor):
    for course in Course.objects.all():
        course.title = course.title.capitalize()
        course.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RunPython(make_course_title_lowercase, course_title_capitalize)
    ]
